### ISSUE TITLE
[Feature Request] Customization to enable full-height AppShell

### ISSUE THREAD

**Issue by t3hmrman** [svelteuidev/svelteui#231]
### Usage example, including component, action, motion, or utility API

`AppShell` currently generates some intermediary components that can't be easily influenced to make it work for a fairly common full height admin page usecase, requiring me to add global styles.

To get an `AppShell` that properly takes up the whole page (which is what I assume people want 90%+ of the time) I need the following global CSS:

```css
 /* Target the first inner wrapper container inside the AppShell */
 .app-shell > div {
   height: 100%;
   display: flex;
   flex-direction: column;
 }
 
 /* Target the wrapper div *for content* which is two layers down inside the AppShell */
 .app-shell > div > div.body {
   flex-grow: 1;
 }
```

Maybe I've missed what the proper way to do this?

Another pain point was that the [`AppShell` sample code](https://www.svelteui.org/core/app-shell) wasn't quite correct (it would be much better to write the actual content that produces *exactly* that output rather than using the `<NavbarContent />` component as shorthand)

### Possible implementation - describe how the feature can be implemented

Adding some extension points to the `Box` used in `AppShell`, allowing it to be full height (or more generally have classes attributable to it)
 

### Do you want to contribute this feature and create a pull request

No
