### ISSUE TITLE
Cannot set class on TextInput input DOM element

### ISSUE THREAD

**Issue by drewbitt** [svelteuidev/svelteui#296]
### What package has an issue

@svelteuidev/core

### A clear and concise description of what the bug is

A `TextInput` when rendered creates something like

```
<div>
  <div>
     <input type="text">
  </div>
</div>
```

When setting `class` on the TextInput, like you would do in Tailwind, you might expect it to apply the classes to the input element (or at least have the option to do so with a similar class prop). However, it sets the classes on the first div element two layers up.

###  Workaround (For now)
You could use some of the classes svelteui is putting on the input, either in an external CSS selector, via css parent-child chaining, or in a :global style tag e.g.
```css
<style>
       // can also scope this with ref
	:global(.svelteui-Input-input) {
		background-color: transparent !important;
	}
</style>
```
However I haven't tested if this classname will always be there in production

### Steps To Reproduce

Use svelteui 0.9

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes
